# Generated by Django 5.1.6 on 2025-03-17 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=20)),
                ('Calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Carbs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Fat', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='QualficationMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('EmailId', models.EmailField(max_length=30)),
                ('ContactNo', models.CharField(max_length=20)),
                ('BirthDate', models.DateField()),
                ('Age', models.DecimalField(decimal_places=2, max_digits=6)),
                ('BloodGroup', models.CharField(max_length=10)),
                ('UserName', models.CharField(max_length=30)),
                ('PassWord', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AreaMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaName', models.CharField(max_length=20)),
                ('CityName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.citymst')),
            ],
        ),
        migrations.CreateModel(
            name='DietitionsMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('EmailId', models.EmailField(max_length=30)),
                ('ContactNo', models.CharField(max_length=20)),
                ('UserName', models.CharField(max_length=30)),
                ('PassWord', models.CharField(max_length=10)),
                ('AreaName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.areamst')),
                ('Qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.qualficationmst')),
            ],
        ),
        migrations.CreateModel(
            name='ShopMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopName', models.CharField(max_length=20)),
                ('AreaName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.areamst')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FoodItemName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.fooditemmst')),
                ('ShopName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.shopmst')),
            ],
        ),
    ]
